-- MySQL Script generated by MySQL Workbench
-- Sat May  4 19:01:22 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `coil_vic` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `coil_vic` DEFAULT CHARACTER SET utf8 ;
USE `coil_vic` ;

-- -----------------------------------------------------
-- Table `coil_vic`.`administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coil_vic`.`administrador` ;

CREATE TABLE IF NOT EXISTS `coil_vic`.`administrador` (
  `idAdministrativo` INT NOT NULL AUTO_INCREMENT,
  `contraseña` VARCHAR(20) NOT NULL,
  `nombreAdministrador` VARCHAR(45) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdministrativo`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `coil_vic`.`colaboraciones_registradas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coil_vic`.`colaboraciones_registradas` ;

CREATE TABLE IF NOT EXISTS `coil_vic`.`colaboraciones_registradas` (
  `Profesor_idProfesor` INT NOT NULL,
  `Colaboración_idColaboración` INT NOT NULL,
  PRIMARY KEY (`Profesor_idProfesor`, `Colaboración_idColaboración`),
  INDEX `fk_Profesor_has_Colaboración_Colaboración1_idx` (`Colaboración_idColaboración` ASC) VISIBLE,
  INDEX `fk_Profesor_has_Colaboración_Profesor1_idx` (`Profesor_idProfesor` ASC) VISIBLE,
  CONSTRAINT `fk_Profesor_has_Colaboración_Colaboración1`
    FOREIGN KEY (`Colaboración_idColaboración`)
    REFERENCES `mydb`.`colaboración` (`idColaboración`),
  CONSTRAINT `fk_Profesor_has_Colaboración_Profesor1`
    FOREIGN KEY (`Profesor_idProfesor`)
    REFERENCES `mydb`.`profesor` (`idProfesor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `coil_vic`.`colaboración`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coil_vic`.`colaboración` ;

CREATE TABLE IF NOT EXISTS `coil_vic`.`colaboración` (
  `idColaboración` INT NOT NULL AUTO_INCREMENT,
  `colaboracióncol` VARCHAR(45) NULL,
  `nombreColaboración` VARCHAR(45) NOT NULL,
  `descripción` TEXT NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NOT NULL,
  `estado` VARCHAR(255) NULL DEFAULT NULL,
  `objetivo` TEXT NOT NULL,
  `temaInterés` VARCHAR(45) NOT NULL,
  `noEstudiantes` INT NULL,
  `perfilEstudiante` TEXT NULL,
  PRIMARY KEY (`idColaboración`))
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `coil_vic`.`estudiante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coil_vic`.`estudiante` ;

CREATE TABLE IF NOT EXISTS `coil_vic`.`estudiante` (
  `correoElectrónico` VARCHAR(255) NOT NULL,
  `Profesor_idProfesor` INT NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`correoElectrónico`),
  INDEX `fk_Estudiante_Profesor1_idx` (`Profesor_idProfesor` ASC) VISIBLE,
  CONSTRAINT `fk_Estudiante_Profesor1`
    FOREIGN KEY (`Profesor_idProfesor`)
    REFERENCES `mydb`.`profesor` (`idProfesor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `coil_vic`.`participa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coil_vic`.`participa` ;

CREATE TABLE IF NOT EXISTS `coil_vic`.`participa` (
  `Estudiante_correoElectrónico` VARCHAR(255) NOT NULL,
  `Colaboración_idColaboración` INT NOT NULL,
  PRIMARY KEY (`Estudiante_correoElectrónico`, `Colaboración_idColaboración`),
  INDEX `fk_Estudiante_has_Colaboración_Colaboración1_idx` (`Colaboración_idColaboración` ASC) VISIBLE,
  INDEX `fk_Estudiante_has_Colaboración_Estudiante1_idx` (`Estudiante_correoElectrónico` ASC) VISIBLE,
  CONSTRAINT `fk_Estudiante_has_Colaboración_Colaboración1`
    FOREIGN KEY (`Colaboración_idColaboración`)
    REFERENCES `mydb`.`colaboración` (`idColaboración`),
  CONSTRAINT `fk_Estudiante_has_Colaboración_Estudiante1`
    FOREIGN KEY (`Estudiante_correoElectrónico`)
    REFERENCES `mydb`.`estudiante` (`correoElectrónico`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coil_vic`.`profesor` ;

CREATE TABLE IF NOT EXISTS `coil_vic`.`profesor` (
  `idProfesor` INT NOT NULL AUTO_INCREMENT,
  `nombreProfesor` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(13) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `tipoProfesor` VARCHAR(45) NOT NULL,
  `país` VARCHAR(45) NOT NULL,
  `Universidad_idUniversidad` INT NOT NULL,
  `area_academica` VARCHAR(255) NULL DEFAULT NULL,
  `correo` VARCHAR(255) NULL DEFAULT NULL,
  `contraseña` VARCHAR(100) NULL DEFAULT NULL,
  `No.Personal` INT NULL,
  `region` VARCHAR(45) NULL,
  `tipoContratación` VARCHAR(45) NULL,
  `categoríaContratación` VARCHAR(45) NULL,
  `disciplina` VARCHAR(45) NULL,
  PRIMARY KEY (`idProfesor`),
  UNIQUE INDEX `uk_usuario` (`usuario` ASC) VISIBLE,
  UNIQUE INDEX `uk_correo` (`correo` ASC) VISIBLE,
  INDEX `fk_Profesor_Universidad_idx` (`Universidad_idUniversidad` ASC) VISIBLE,
  UNIQUE INDEX `No.Personal_UNIQUE` (`No.Personal` ASC) VISIBLE,
  CONSTRAINT `fk_Profesor_Universidad`
    FOREIGN KEY (`Universidad_idUniversidad`)
    REFERENCES `mydb`.`universidad` (`idUniversidad`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb3
COMMENT = '	';


-- -----------------------------------------------------
-- Table `coil_vic`.`syllabus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coil_vic`.`syllabus` ;

CREATE TABLE IF NOT EXISTS `coil_vic`.`syllabus` (
  `idSyllabus` INT NOT NULL AUTO_INCREMENT,
  `actividad` VARCHAR(30) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `responsable` VARCHAR(45) NOT NULL,
  `colaboración_idColaboración` INT NOT NULL,
  PRIMARY KEY (`idSyllabus`),
  INDEX `fk_syllabus_colaboración1_idx` (`colaboración_idColaboración` ASC) VISIBLE,
  CONSTRAINT `fk_syllabus_colaboración1`
    FOREIGN KEY (`colaboración_idColaboración`)
    REFERENCES `mydb`.`colaboración` (`idColaboración`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `coil_vic`.`universidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coil_vic`.`universidad` ;

CREATE TABLE IF NOT EXISTS `coil_vic`.`universidad` (
  `idUniversidad` INT NOT NULL AUTO_INCREMENT,
  `país` VARCHAR(45) NOT NULL,
  `nombreUniversidad` VARCHAR(45) NOT NULL,
  `idioma` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUniversidad`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
