-- MySQL Script generated by MySQL Workbench
-- Tue Mar  5 16:23:41 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema COIL_VIC
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `COIL_VIC` ;

-- -----------------------------------------------------
-- Schema COIL_VIC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `COIL_VIC` DEFAULT CHARACTER SET utf8 ;
USE `COIL_VIC` ;

-- -----------------------------------------------------
-- Table `COIL_VIC`.`Universidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COIL_VIC`.`Universidad` (
  `idUniversidad` INT NOT NULL,
  `país` VARCHAR(45) NOT NULL,
  `nombreUniversidad` VARCHAR(45) NOT NULL,
  `idioma` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUniversidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `COIL_VIC`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COIL_VIC`.`Administrador` (
  `idAdministrativo` INT NOT NULL,
  `contraseña` VARCHAR(20) NOT NULL,
  `nombreAdministrador` VARCHAR(45) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdministrativo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `COIL_VIC`.`Curso-Taller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COIL_VIC`.`Curso-Taller` (
  `nombreCursoTaller` VARCHAR(45) NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NOT NULL,
  `requisitos` VARCHAR(45) NULL,
  PRIMARY KEY (`nombreCursoTaller`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `COIL_VIC`.`Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COIL_VIC`.`Profesor` (
  `idProfesor` INT NOT NULL,
  `nombreProfesor` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `tipoProfesor` VARCHAR(45) NOT NULL,
  `país` VARCHAR(45) NOT NULL,
  `Universidad_idUniversidad` INT NOT NULL,
  `Administrador_idAdministrativo` INT NOT NULL,
  `Curso-Taller_nombreCursoTaller` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProfesor`),
  INDEX `fk_Profesor_Universidad_idx` (`Universidad_idUniversidad` ASC) VISIBLE,
  INDEX `fk_Profesor_Administrador1_idx` (`Administrador_idAdministrativo` ASC) VISIBLE,
  INDEX `fk_Profesor_Curso-Taller1_idx` (`Curso-Taller_nombreCursoTaller` ASC) VISIBLE,
  CONSTRAINT `fk_Profesor_Universidad`
    FOREIGN KEY (`Universidad_idUniversidad`)
    REFERENCES `COIL_VIC`.`Universidad` (`idUniversidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profesor_Administrador1`
    FOREIGN KEY (`Administrador_idAdministrativo`)
    REFERENCES `COIL_VIC`.`Administrador` (`idAdministrativo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profesor_Curso-Taller1`
    FOREIGN KEY (`Curso-Taller_nombreCursoTaller`)
    REFERENCES `COIL_VIC`.`Curso-Taller` (`nombreCursoTaller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `COIL_VIC`.`Estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COIL_VIC`.`Estudiante` (
  `correoElectrónico` VARCHAR(255) NOT NULL,
  `Profesor_Administrador_idAdministrativo` INT NOT NULL,
  `Profesor_Colaboración_nombreColaboración` VARCHAR(45) NOT NULL,
  `Profesor_idProfesor` INT NOT NULL,
  PRIMARY KEY (`correoElectrónico`),
  INDEX `fk_Estudiante_Profesor1_idx` (`Profesor_idProfesor` ASC) VISIBLE,
  CONSTRAINT `fk_Estudiante_Profesor1`
    FOREIGN KEY (`Profesor_idProfesor`)
    REFERENCES `COIL_VIC`.`Profesor` (`idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `COIL_VIC`.`Colaboración`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COIL_VIC`.`Colaboración` (
  `idColaboración` INT NOT NULL,
  `descripción` VARCHAR(45) NOT NULL,
  `fechaFin` DATE NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `nombreColaboración` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idColaboración`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `COIL_VIC`.`Facilitador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COIL_VIC`.`Facilitador` (
  `idFacilitador` INT NOT NULL,
  `nombreFacilitador` VARCHAR(45) NOT NULL,
  `Curso-Taller_nombreCursoTaller` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFacilitador`),
  INDEX `fk_Facilitador_Curso-Taller1_idx` (`Curso-Taller_nombreCursoTaller` ASC) VISIBLE,
  CONSTRAINT `fk_Facilitador_Curso-Taller1`
    FOREIGN KEY (`Curso-Taller_nombreCursoTaller`)
    REFERENCES `COIL_VIC`.`Curso-Taller` (`nombreCursoTaller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `COIL_VIC`.`Colaboraciones registradas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COIL_VIC`.`Colaboraciones registradas` (
  `Profesor_idProfesor` INT NOT NULL,
  `Colaboración_idColaboración` INT NOT NULL,
  PRIMARY KEY (`Profesor_idProfesor`, `Colaboración_idColaboración`),
  INDEX `fk_Profesor_has_Colaboración_Colaboración1_idx` (`Colaboración_idColaboración` ASC) VISIBLE,
  INDEX `fk_Profesor_has_Colaboración_Profesor1_idx` (`Profesor_idProfesor` ASC) VISIBLE,
  CONSTRAINT `fk_Profesor_has_Colaboración_Profesor1`
    FOREIGN KEY (`Profesor_idProfesor`)
    REFERENCES `COIL_VIC`.`Profesor` (`idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profesor_has_Colaboración_Colaboración1`
    FOREIGN KEY (`Colaboración_idColaboración`)
    REFERENCES `COIL_VIC`.`Colaboración` (`idColaboración`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `COIL_VIC`.`Participa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COIL_VIC`.`Participa` (
  `Estudiante_correoElectrónico` VARCHAR(255) NOT NULL,
  `Colaboración_idColaboración` INT NOT NULL,
  PRIMARY KEY (`Estudiante_correoElectrónico`, `Colaboración_idColaboración`),
  INDEX `fk_Estudiante_has_Colaboración_Colaboración1_idx` (`Colaboración_idColaboración` ASC) VISIBLE,
  INDEX `fk_Estudiante_has_Colaboración_Estudiante1_idx` (`Estudiante_correoElectrónico` ASC) VISIBLE,
  CONSTRAINT `fk_Estudiante_has_Colaboración_Estudiante1`
    FOREIGN KEY (`Estudiante_correoElectrónico`)
    REFERENCES `COIL_VIC`.`Estudiante` (`correoElectrónico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiante_has_Colaboración_Colaboración1`
    FOREIGN KEY (`Colaboración_idColaboración`)
    REFERENCES `COIL_VIC`.`Colaboración` (`idColaboración`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
